config/routes.rb
Mail::Application.routes.draw do

  root 'application#index'

  resources :churches do
    resources :events
  end






  

end

app/models/church.rb
class Church < ActiveRecord::Base
has_many :events, dependent: :destroy

validates :name, presence: true, length: {minimum:5}
validates :location, presence: true, length: {minimum:10}

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :church
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    @events = Event.all
  end
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController

def index
  @churches = Church.all
end

def new
  @church = Church.new
end

def create
  @church = Church.new(params.require(:church).permit(:name, :location))
  if @church.save
     redirect_to churches_path
  else
     render 'new'
  end
end

def edit
  @church = Church.find(params[:id])
end

def update
  @church = Church.find(params[:id])
  if @church.update(params.require(:church).permit(:name, :location))
     redirect_to churches_path
  else
     render 'edit'
  end
end

def show
  @church = Church.find(params[:id])
end

def destroy
  @church = Church.find(params[:id])
  @church.destroy
  redirect_to churches_path
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

def create
  @church = Church.find(params[:church_id]) 
  @event = @church.events.create(params[:event].permit(:name, :desc)) 
  redirect_to church_path(@church) 
end

def destroy 
  @church = Church.find(params[:church_id]) 
  @event = @church.events.find(params[:id]) 
  @event.destroy 
  redirect_to church_path(@church) 
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/application/index.html.erb
<% @events.reverse.each do |event| %>
<table align=center>
  <tr>
     <th colspan="2">
      <%=event.name %>
    </th>
  </tr>
  <tr>
    <td>
      <b>Description: </b><%= event.desc %>
    </td>
    <td>
      <b>Where: </b><%= event.church.name %>
    </td>
  </tr>
  <tr>
    <td colspan=2>
      <b>Address: </b><%= event.church.location %>
    </td>
  </tr>
</table>
<% end %>

app/views/application/live.html.erb
<%= jwplayer_assets %>

<h2>JFM Live Service</h2>
<div id='my-video'>Your player is loading....</div>

<script type="text/javascript">
  jwplayer("my-video").setup({
    playlist: [{
      image: "http://www.jesusfamilytv.com/images/home_img.jpg",
      sources: [{ 
          file: "rtmp://184.95.35.92:1936/8046/8046" 
        },{
          file: "http://184.95.35.92:1936/8046/8046/playlist.m3u8" 
      }]
    }],
    height: 360,
    logo: {
      file: 'http://www.jesusfamilytv.com/images/jw_logo.png',
      link: 'http://www.jesusfamilytv.com'
    },
    primary: "flash",
    autostart: false,
    stretching: 'exactfit',
    ga: {
      idstring: "8046",
      trackingobject: "pageTracker"
    },
    width: 640
  });                    
</script>
</div>

app/views/churches/edit.html.erb
<h1> Edit Church Details </h1>

<%= form_for @church do |f| %>
<% if @church.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@church.errors.count, "error") %> prohibited
this church from being saved:</h2>
<ul>
<% @church.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :location %><br>
<%= f.text_area :location %>
</p>

<p>
<%= f.submit%>
</p>

<% end %>

<%= link_to "Home", churches_path %>

app/views/churches/index.html.erb
<h1> Welcome Church </h1>
<table>
<tr>
<strong> <th> Name </th> <th> Location </th> </strong>
</tr>
<% @churches.each do |f| %>
<tr>
<td> <%= f.name %></td>
<td> <%= f.location %></td>
<td> <%= link_to "Edit", edit_church_path(f.id) %> </td>
<td> <%= link_to "Show", church_path(f.id)  %> </td>
<td> <%= link_to "Destroy", {action: :destroy, id: f.id}, method: :delete, data: {confirm: 'Are you Sure?'}  %> </td>
<% end %>
</table>
<br><br>
<%= link_to "Add New Church", new_church_path %>

app/views/churches/new.html.erb
<h1> Add New Church </h1>
<%= form_for @church do |f| %>
<% if @church.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@church.errors.count, "error") %> prohibited
this church from being saved:</h2>
<ul>
<% @church.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :location %><br>
<%= f.text_area :location %>
</p>

<p>
<%= f.submit%>
</p>

<% end %>

<%= link_to "Home", churches_path %>

app/views/churches/show.html.erb
<h1> Show Church Details </h1>

<strong> Name: </strong>
<%= @church.name %><br>
<strong>Location: </strong>
<%= @church.location %>
<br>

<h2>Event Details</h2> 
<table>
<tr>
<th>Name</th><th>Descrption</th>
</tr>
<% @church.events.each do |f| %> 
<tr>
<td><%= f.name %></td> 
<td><%= f.desc %> </td>
<td><%= link_to 'Destroy Event', [f.church, f], method: :delete, data: { confirm: 'Are you sure?' } %> </td>
</tr>
<% end %> 
</table>

<h2> Add Church Events </h2>
<%= form_for ([@church, @church.events.build]) do |f| %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :desc %><br>
<%= f.text_area :desc %>
</p>
<p>
<%= f.submit%>
</p>
<% end %>
<br>
<%= link_to "Home", churches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JFM CHURCH BOOK</title>
  <link rel="shortcut icon" href="http://www.jesusfamilytv.com/favicon.ico" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>